apiVersion: v1
kind: Namespace
metadata:
  name: mysql
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pgsql
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
