apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgsql
  namespace: pgsql
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: pgsql
    server: {{ .Values.spec.destination.server }}
  project: pawan
  source:
    path: pgsql
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
